name: app_ui
description: Djamo Design System Plugin
version: 0.0.1
homepage: "djamo.ci"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  gap:
  shimmer:
  expansion_tile_card:
  country_calling_code_picker:
  mask_text_input_formatter:
  cached_network_image:
  charts_flutter:
  percent_indicator:
  dotted_line:
  custom_sliding_segmented_control:
  icon_font_generator:
  countup:
  flutter_svg: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/design_tokens/iconography/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  asset:
    enabled: true
    style: snake-case
  fonts:
    enabled: false
    style: snake-case
  colors:
    enabled: true

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    # Images
    - assets/images/

    # Icons
    - assets/icons/colored/
    # - assets/icons/3d/
    - assets/icons/svg/

    # GIF
    - assets/gif/

  fonts:
    - family: Futura PT
      fonts:
        - asset: assets/fonts/futura_pt/FuturaPT-Bold.ttf
          weight: 800

        - asset: assets/fonts/futura_pt/FuturaPT-BoldOblique.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Book.ttf
          weight: 400

        - asset: assets/fonts/futura_pt/FuturaPT-BookOblique.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-DemiBold.ttf
          weight: 600

        - asset: assets/fonts/futura_pt/FuturaPT-DemiBoldOblique.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-ExtraBold.ttf
          weight: 900

        - asset: assets/fonts/futura_pt/FuturaPT-ExtraBoldOblique.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Heavy.ttf
          weight: 700

        - asset: assets/fonts/futura_pt/FuturaPT-HeavyOblique.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Light.ttf
          weight: 300

        - asset: assets/fonts/futura_pt/FuturaPT-LightOblique.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Medium.ttf
          weight: 500

        - asset: assets/fonts/futura_pt/FuturaPT-MediumOblique.ttf
          weight: 500
          style: italic

    - family: App Icons
      fonts:
        - asset: assets/fonts/app_icons/app-icons.ttf

    - family: OCRAStd
      fonts:
        - asset: assets/fonts/ocrastd/OCRAStd.otf
