name: app_ui_m2
description: Djamo Design System library
version: 1.1.0
homepage: "djamo.ci"
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  gap:
  shimmer: ^3.0.0
  expansion_tile_card:
  cached_network_image:
  percent_indicator:
  dotted_line:
  custom_sliding_segmented_control:
  icon_font_generator:
  countup:
  flutter_svg: ^2.0.10+1
  app_ui:
    git:
      url: git@github.com:djamoapp/djamo-mobile-v3.git
      path: packages/app_ui
      ref: app_ui-v0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/design_tokens/iconography/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  asset:
    enabled: true
    style: snake-case
  fonts:
    enabled: false
    style: snake-case
  colors:
    enabled: true
  assets:
    outputs:
      package_parameter_enabled: true

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    # Images
    - assets/images/
    - assets/illustrations/

    # Icons
    - assets/icons/colored/
    - assets/icons/icon_3d/
    - assets/icons/svg/

    # GIF
    - assets/gif/

  fonts:
    - family: Futura PT
      fonts:
        - asset: assets/fonts/futura_pt/FuturaPT-Bold.ttf
          weight: 800

        - asset: assets/fonts/futura_pt/FuturaPT-BoldOblique.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Book.ttf
          weight: 400

        - asset: assets/fonts/futura_pt/FuturaPT-BookOblique.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-DemiBold.ttf
          weight: 600

        - asset: assets/fonts/futura_pt/FuturaPT-DemiBoldOblique.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-ExtraBold.ttf
          weight: 900

        - asset: assets/fonts/futura_pt/FuturaPT-ExtraBoldOblique.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Heavy.ttf
          weight: 700

        - asset: assets/fonts/futura_pt/FuturaPT-HeavyOblique.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Light.ttf
          weight: 300

        - asset: assets/fonts/futura_pt/FuturaPT-LightOblique.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/futura_pt/FuturaPT-Medium.ttf
          weight: 500

        - asset: assets/fonts/futura_pt/FuturaPT-MediumOblique.ttf
          weight: 500
          style: italic

    - family: App Icons
      fonts:
        - asset: assets/fonts/app_icons/app-icons.ttf
    - family: OCRAStd
      fonts:
        - asset: assets/fonts/ocrastd/OCRAStd.otf
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Bold.ttf
          weight: 800
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/gt_walsheim_pro/GTWalsheimPro-Thin.ttf
          weight: 300
